source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'jwt', '~> 1.5', '>= 1.5.4'
gem 'simple_command', '~> 0.0.9'
gem 'kaminari'
gem 'acts_as_paranoid'
gem 'acts_as_list'
gem 'state_machines'
gem 'twitter_cldr'
gem 'activemerchant'
gem 'awesome_nested_set', '~> 3.2'
gem 'cancan', '~> 1.6', '>= 1.6.10'
gem 'friendly_id', '~> 5.3'
gem 'monetize', '~> 1.9', '>= 1.9.4'
gem 'paranoia', '~> 2.4', '>= 2.4.2'
gem 'mini_magick', '~> 4.10', '>= 4.10.1'
gem 'premailer-rails', '~> 1.10', '>= 1.10.3'
gem 'ransack', '~> 2.3', '>= 2.3.2'
gem 'responders', '~> 3.0'
gem 'state_machines-activerecord', '~> 0.6.0'
gem 'stringex', '~> 2.8', '>= 2.8.5'
gem 'doorkeeper'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rubocop', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
